

package trainingcore;

import java.util.*;
import java.io.Serializable;
import de.hybris.platform.util.*;
import de.hybris.platform.core.*;
import de.hybris.platform.jalo.JaloBusinessException;
import de.hybris.platform.jalo.type.*;
import de.hybris.platform.persistence.type.*;
import de.hybris.platform.persistence.enumeration.*;
import de.hybris.platform.persistence.property.PersistenceManager;
import de.hybris.platform.persistence.*;

/**
 * Generated by hybris Platform.
 */
@SuppressWarnings({"cast","unused","boxing","null", "PMD"})
public class GeneratedTypeInitializer extends AbstractTypeInitializer
{
	/**
	 * Generated by hybris Platform.
	 */
	public GeneratedTypeInitializer( ManagerEJB manager, Map params )
	{
		super( manager, params );
	}


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected void performRemoveObjects( ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// no-op by now
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateTypes
	
	
		createItemType(
			"LiquorProduct",
			"Product",
			org.training.core.jalo.LiquorProduct.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"LiquorBottleSizeVariantProduct",
			"VariantProduct",
			org.training.core.jalo.LiquorBottleSizeVariantProduct.class,
			null,
			false,
			null,
			false
		);
	
		createEnumerationType(
			"BottleSizeEnum",
			null
		);
	
		createCollectionType(
			"BottleSizeSet",
			"BottleSizeEnum",
			CollectionType.SET
		);
	
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performModifyTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performModifyTypes
	

	
	
				single_createattr_LiquorBottleSizeVariantProduct_bottleSize();
			

	}

	
	public void single_createattr_LiquorBottleSizeVariantProduct_bottleSize() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"LiquorBottleSizeVariantProduct", 
					"bottleSize",  
					null,
					"BottleSizeSet",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateObjects( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateObjects
	
	
		createEnumerationValues(
			"BottleSizeEnum",
			true,
			Arrays.asList( new String[] {
			
				"SAMPLE",
				"HALF",
				"REGULAR",
				"MAGNUM"
			} )
		);
	
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"LiquorProduct",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"LiquorBottleSizeVariantProduct",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_LiquorBottleSizeVariantProduct_bottleSize();
		
				setDefaultProperties(
					"BottleSizeSet",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"BottleSizeEnum",
					true,
					true,
					null
				);
			
	}


		
						public void single_setAttributeProperties_LiquorBottleSizeVariantProduct_bottleSize() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"LiquorBottleSizeVariantProduct", 
								"bottleSize",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
}

	